### ISSUE TITLE
Problems with extensions

### ISSUE THREAD

**Issue by nr458h** [FabianWilkens/snserver_ynh#9]
Hi its me again ;)

with the latest version 3.13.6 ynh4 I updated my Standardnoteserver (bevor I was on the beta version)
Since than I get errors in the desktop clients and I can't reach your.domain.tdl/extensions anymore
When I try to remove the extensions within the admin panel it says

> Error while execution action 'remove extensions' of app: return code 127

The Logs of this operation can be found [here](paste.yunohost.org/raw/iweqidesar)

Thanks in advance

**Comment by FabianWilkens** [comment]
Hey,

thanks for reporting.

Year the action feature doesn't exist anymore.
I wanted to make it optional to install the extensions.
But then I decided that it was much easier to simply always install the extensions. 

It is correct that you can no longer reach your.domain.tdl/extensions. Since we no longer need this page, since we now have the repository. Accessible at your.domain.tdl/extensions/repo.json


If I understood correctly, have you updated from the testing branch to your live instance? I did not test this in the upgrade tests.
I tested only from the master branch to this new version.

And what errors do you get at the desktop clients?

**Comment by nr458h** [comment]
I missed that - with the hint for the repo everythimg works now - except the filesafe extension. I can not find that in the repo.

As always! Thanks for your quick reply and your help
Just awesomeñ

**Comment by FabianWilkens** [comment]
Nice to hear that it works now.
With the filesafe extension it is the same problem like the secure-spreadsheet extension #8.
But the filesafe system is also integrated in the bold editor.

**Comment by nr458h** [comment]
As there is no problem any longer closing this
